# apiversion: v1
# kind: Pod   
# metadata:
#  name: multi-container
#  labels:
#   purpose: multi-container
#   spec:
#    containers:     #This pod consists two conatiner nginx and alamalinux
#     - name: nginx
#       image: nginx
#     - name: alamalinux
#       image: alamalinux:9
#       command: ["sleep", "1000"]

apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    purpose: multi-container
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]